title: "IBS - Índice de Bioactividad del Suelo"
description: "Marco abierto para la evaluación rápida de la actividad microbiana"
baseurl: "/ibs"
url: "https://stndcx.github.io"

permalink: /blog/:year/:month/:day/:title/
paginate: 5
paginate_path: /blog/page:num/

theme: minima

source: src

plugins:
  - jekyll-feed
  - jekyll-seo-tag

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

collections:
  events:
    output: false
    sort_by: date